services:
  whpg7_cdw:
    build:
      context: .
      secrets:
        - repo_token
    image: whpg7_cdw
    platform: linux/amd64
    container_name: cdw
    hostname: cdw
    tty: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    networks:
      # whpg-network:
      converged-analytics-network:
    ports:
      - "5432:5432"
    volumes:
      - master:/data/master

  whpg7_seg1:
    image: whpg7_cdw
    depends_on:
      - whpg7_cdw
    container_name: sdw1
    hostname: sdw1
    tty: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    platform: linux/amd64
    networks:
      # whpg-network:
      converged-analytics-network:
    volumes:
      - sdw1_primary1:/data1/primary
      - sdw1_primary2:/data2/primary
      - sdw1_mirror1:/data1/mirror
      - sdw1_mirror2:/data2/mirror

  whpg7_seg2:
    image: whpg7_cdw
    depends_on:
      - whpg7_cdw
    container_name: sdw2
    hostname: sdw2
    tty: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    platform: linux/amd64
    networks:
      # whpg-network:
      converged-analytics-network:
    volumes:
      - sdw2_primary1:/data1/primary
      - sdw2_primary2:/data2/primary
      - sdw2_mirror1:/data1/mirror
      - sdw2_mirror2:/data2/mirror

networks:
  # whpg-network:
  #   driver: bridge
  #   name: whpg-network

  converged-analytics-network:
    external: true
    name: converged-analytics-network

volumes:
  master:
  sdw1_primary1:
  sdw1_primary2:
  sdw1_mirror1:
  sdw1_mirror2:
  sdw2_primary1:
  sdw2_primary2:
  sdw2_mirror1:
  sdw2_mirror2:

secrets:
  repo_token:
    environment: EDB_SUBSCRIPTION_TOKEN

